// <copyright file="AuctionMailboxEntry.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.EntityFramework.Model;

using System.ComponentModel.DataAnnotations.Schema;
using MUnique.OpenMU.Persistence;

/// <summary>
/// The Entity Framework Core implementation of <see cref="MUnique.OpenMU.DataModel.Entities.AuctionMailboxEntry"/>.
/// </summary>
[Table(nameof(AuctionMailboxEntry), Schema = SchemaNames.AccountData)]
internal partial class AuctionMailboxEntry : MUnique.OpenMU.DataModel.Entities.AuctionMailboxEntry, IIdentifiable
{


    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the identifier of <see cref="Item"/>.
    /// </summary>
    public Guid? ItemId { get; set; }

    /// <summary>
    /// Gets the raw object of <see cref="Item" />.
    /// </summary>
    [ForeignKey(nameof(ItemId))]
    public Item RawItem
    {
        get => base.Item as Item;
        set => base.Item = value;
    }

    /// <inheritdoc/>
    [NotMapped]
    public override MUnique.OpenMU.DataModel.Entities.Item Item
    {
        get => base.Item;set
        {
            base.Item = value;
            this.ItemId = this.RawItem?.Id;
        }
    }

    /// <summary>
    /// Gets or sets the identifier of <see cref="ItemStorage"/>.
    /// </summary>
    public Guid? ItemStorageId { get; set; }

    /// <summary>
    /// Gets the raw object of <see cref="ItemStorage" />.
    /// </summary>
    [ForeignKey(nameof(ItemStorageId))]
    public ItemStorage RawItemStorage
    {
        get => base.ItemStorage as ItemStorage;
        set => base.ItemStorage = value;
    }

    /// <inheritdoc/>
    [NotMapped]
    public override MUnique.OpenMU.DataModel.Entities.ItemStorage ItemStorage
    {
        get => base.ItemStorage;set
        {
            base.ItemStorage = value;
            this.ItemStorageId = this.RawItemStorage?.Id;
        }
    }


    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }


}
