// <copyright file="AuctionMailboxEntry.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.BasicModel;

using MUnique.OpenMU.Persistence.Json;

/// <summary>
/// A plain implementation of <see cref="AuctionMailboxEntry"/>.
/// </summary>
public partial class AuctionMailboxEntry : MUnique.OpenMU.DataModel.Entities.AuctionMailboxEntry, IIdentifiable, IConvertibleTo<AuctionMailboxEntry>
{

    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets the raw object of <see cref="Item" />.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("item")]
    [System.Text.Json.Serialization.JsonPropertyName("item")]
    public Item RawItem
    {
        get => base.Item as Item;
        set => base.Item = value;
    }

    /// <inheritdoc/>
    [Newtonsoft.Json.JsonIgnore]
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Entities.Item Item
    {
        get => base.Item;
        set => base.Item = value;
    }

    /// <summary>
    /// Gets the raw object of <see cref="ItemStorage" />.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("itemStorage")]
    [System.Text.Json.Serialization.JsonPropertyName("itemStorage")]
    public ItemStorage RawItemStorage
    {
        get => base.ItemStorage as ItemStorage;
        set => base.ItemStorage = value;
    }

    /// <inheritdoc/>
    [Newtonsoft.Json.JsonIgnore]
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Entities.ItemStorage ItemStorage
    {
        get => base.ItemStorage;
        set => base.ItemStorage = value;
    }


    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    /// <inheritdoc/>
    public AuctionMailboxEntry Convert() => this;
}
